name: route_manager
description: A package to manage and simplify routing with Navigator 2.0.
version: 2.0.1+1
homepage: "https://github.com/mobilesoftcode/route_manager.git"
issue_tracker: "https://github.com/mobilesoftcode/route_manager/issues"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.2 <6.0.0"

flutter: